### ISSUE TITLE
Le robot drift en allant en ligne droite

### ISSUE THREAD

**Issue by marchif1971** [empereurs6851/betabot2018#4]
Pourrait être corrigé en utilisant la fonction "correctRotationWithNavX" dans subsystems/DriveBase.java, fonction "public void drive(double moveValue, double rotateValue)" à la place de "correctRotationWithEncoders", donc tenter de remplacer la ligne 63 actuellement "//rotateValue = correctRotationWithEncoders(moveValue, rotateValue);" par "rotateValue = correctRotationWithNavX(moveValue, rotateValue);".

La fonction NavX.getCompassHeading() ne fonctionnait pas mais navX.getangle() oui et c'est ce qu'utilise "correctRotationWithNavX".

**Comment by jpcotekinova** [comment]
Fait mais pas teste

**Comment by marchif1971** [comment]
Testé, mais ça semble pas changer grand chose, à tester plus intensément avec le mode automatique.

**Comment by marchif1971** [comment]
J'ai modifié MoveTime pour corriger l'angle afin de conserver l'angle de départ. Fonctionne, sauf qu'il faut limiter la correction pour éviter que le robot parte en vrille.

**Comment by marchif1971** [comment]
Limité la vitesse de rotation en correction.
