### ISSUE TITLE
Le robot ne tourne pas précisément à l'angle désiré

### ISSUE THREAD

**Issue by marchif1971** [empereurs6851/betabot2018#5]
La fonction NavX.getCompassHeading() ne fonctionnait pas mais navX.getangle() oui et c'est ce qu'utilise "correctRotationWithNavX".

Modifier "commands/driving/MoveTime.java" pour utilise navX.getangle() : 

- Ajouter un paramètre à la fonction qui sera l'angle de rotation désiré "double rotationangle".
- Ajouter une variable private qui sera l'angle de départ "double angledepart".
- Ajouter une variable private qui sera l'angle de rotation desiré "double rotationangle".
- Ajouter à "initialize()" l'enregistrement de l'angle de départ du mouvement
- Dans IsFinished, ajouter que : si la commande n'est pas une rotation (rotationangle =0) conserver la logique actuelle pour "return true;" sinon si rotationangle<0 return (NavX.getangle()<(angledepart+rotationangle)) sinon return (NavX.getangle()>(angledepart+rotationangle))

**Comment by jpcotekinova** [comment]
C'est super. Noubli pas de gèrer les angle negatif si get angle t'en retourne.

**Comment by marchif1971** [comment]
Je pense que c'est ce que mon IsFinished fait si la commande "rotationangle" est dans le même sens que NavX.getangle().

**Comment by jpcotekinova** [comment]
Fait et pas teste

**Comment by marchif1971** [comment]
Testé et ça fonctionne!

**Comment by jpcotekinova** [comment]
Great !!!

*Jean-Philippe Côté*
Gestionnaire des groupes Logiciel et Contrôle
Group Leader Software and Control




514-277-3777

514-268-9219

jpcote@kinova.ca

4333 boul. de la Grande-Allée, Boisbriand (QC)
<https://maps.google.com/?q=4333+Grande-All%C3%A9e+Boulevard,+Boisbriand+QC++J7H+1M7&entry=gmail&source=g>

<https://maps.google.com/?q=4333+boul.+de+la+Grande-All%C3%A9e,+Boisbriand+(QC)++%C2%A0+J7H+1M7&entry=gmail&source=g>J7H
1M7
<https://maps.google.com/?q=4333+Grande-All%C3%A9e+Boulevard,+Boisbriand+QC++J7H+1M7&entry=gmail&source=g>
 →

kinovarobotics.com <http://www.kinovarobotics.com/>   Facebook
<http://facebook.com/kinovarobotics/>  Twitter
<http://twitter.com/kinovarobotics>  LinkedIn
<https://www.linkedin.com/company/kinova/>  YouTube
<https://www.youtube.com/user/Kinovarobotics>

The information contained in this email message is private and
confidential. It is intended for the exclusive use by the recipient named
above. If you are not the intended recipient, be advised that disclosing,
copying, distributing or taking any action in reliance on the contents of
this information is strictly prohibited. If you have been sent this email
by error, please destroy it and immediately inform us at
info@kinovarobotics.com.
